version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/app.db
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    ports:
      - "${API_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT:-8000}/api
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  data:
    driver: local
  uploads:
    driver: local