"""initial

Revision ID: e57a1c1a5dbf
Revises: 
Create Date: 2025-08-23 23:48:08.187146

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e57a1c1a5dbf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("hobby",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("color", sa.String(length=50), nullable=True),
    sa.Column("icon", sa.String(length=100), nullable=True),
    sa.Column("parent_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["parent_id"], ["hobby.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name")
    )
    op.create_table("hobbytype",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("key", sa.String(length=100), nullable=False),
    sa.Column("title", sa.String(length=255), nullable=False),
    sa.Column("schema_json", sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("key")
    )
    op.create_table("user",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("username", sa.String(length=100), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=True),
    sa.Column("bio", sa.Text(), nullable=True),
    sa.Column("avatar_path", sa.String(length=500), nullable=True),
    sa.Column("password_hash", sa.String(length=255), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("username")
    )
    op.create_table("entry",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("hobby_id", sa.Integer(), nullable=False),
    sa.Column("type_key", sa.String(length=100), nullable=False),
    sa.Column("title", sa.String(length=500), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("tags", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["hobby_id"], ["hobby.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["type_key"], ["hobbytype.key"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_entry_hobby", "entry", ["hobby_id"], unique=False)
    op.create_index("idx_entry_type", "entry", ["type_key"], unique=False)
    op.create_table("entrymedia",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("entry_id", sa.Integer(), nullable=False),
    sa.Column("kind", sa.String(length=20), nullable=True),
    sa.Column("file_path", sa.String(length=500), nullable=False),
    sa.Column("width", sa.Integer(), nullable=True),
    sa.Column("height", sa.Integer(), nullable=True),
    sa.Column("duration", sa.Float(), nullable=True),
    sa.Column("meta_json", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_media_entry", "entrymedia", ["entry_id"], unique=False)
    op.create_table("entryprop",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("entry_id", sa.Integer(), nullable=False),
    sa.Column("key", sa.String(length=255), nullable=False),
    sa.Column("value_text", sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("entry_id", "key")
    )
    op.create_index("idx_entryprop_entry", "entryprop", ["entry_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_entryprop_entry", table_name="entryprop")
    op.drop_table("entryprop")
    op.drop_index("idx_media_entry", table_name="entrymedia")
    op.drop_table("entrymedia")
    op.drop_index("idx_entry_type", table_name="entry")
    op.drop_index("idx_entry_hobby", table_name="entry")
    op.drop_table("entry")
    op.drop_table("user")
    op.drop_table("hobbytype")
    op.drop_table("hobby")
    # ### end Alembic commands ###
